# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e81c09b09af7969d274d382c68eb30f9ee65ec751aa62d1003baefbc35576f1440a510eae756e60c4212bcc559b6c367018d6863c12642c4b67237837f96a55

test:
  secret_key_base: a95f5a9a394d0c3ac5c813edffa4de4f16cf9719794438ee234be2c54e7c5ea441427903310e587a50f8aa48ae15c98c018218b54a7512e579a3eac62dcac840

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
